### ISSUE TITLE
How to Add Multiple Files and Folders to an Archive Using a Single Command

### ISSUE THREAD

**Issue by byplt** [fcorbelli/zpaqfranz#136] opened 2024-10-11 18:43 UTC
Similar to 7-Zip;
`7z a archive.7z @files.txt`

files.txt:
```
D:\app.exe
D:\testfolder\
```

**Comment by fcorbelli** [comment] 2024-10-11 18:57
-input

**Comment by byplt** [comment] 2024-10-11 19:11
thanks

**Comment by byplt** [comment] 2024-10-11 19:48
Another question:
If I want to add these files to a different folder in the archive, how can I do that?

for example;
`zpaqfranz a archive.zpaq -input "files.txt" -to "in_archive_folder/"`

And when listing the archive contents:

`zpaqfranz l archive.zpaq`

Output:
```
...
in_archive_folder\file1.txt
in_archive_folder\file2.txt
...
```

**Comment by fcorbelli** [comment] 2024-10-11 19:54
-find and -replace

**Comment by byplt** [comment] 2024-10-11 20:51
I think there might be a bug:

(working) `zpaqfranz.exe a archive.zpaq "D:\files" -find "D:\files" -replace "test"`
(not working) `zpaqfranz.exe a archive.zpaq -input "D:\filepaths.txt" -find "D:\files" -replace "test"`

Nothing happens.

**Comment by fcorbelli** [comment] 2024-10-12 12:10
...Because you are using Windows

Please try, with the upgrade -force, the current 60.8b. 
This should fix

**Comment by byplt** [comment] 2024-10-12 13:48
It's working, thank you for your effort! There's one more thing:
When using -find and -replace with -input, the archive keeps growing.

For example, when running this command multiple times:
`zpaqfranz.exe a archive.zpaq -input "D:\filepaths.txt" -find "D:\files" -replace "test"`
output will be;

![Ekran görüntüsü 2024-10-12 164512](https://github.com/user-attachments/assets/195ee70a-9c33-4d81-a532-7078d4b8f1ea)

but, I guess, there should be warning, like;

![Ekran görüntüsü 2024-10-12 164649](https://github.com/user-attachments/assets/6f523aec-34f9-4f8b-99ef-ac2dd52c32ea)

**Comment by fcorbelli** [comment] 2024-10-12 13:57
-find/replace will start again the archiving
You can use -to, this should be "smarter"

**Comment by byplt** [comment] 2024-10-13 16:56
thx

**Comment by byplt** [comment] 2024-10-15 18:32
I understand,

It works like folder synchronization. I was asking if there's a way to turn that off. I only want to include conflicting files in the process. This issue happens when adding folders, but not when adding files one by one. Also, using the -until switch makes version control quite difficult for automation.

![image](https://github.com/user-attachments/assets/b2817178-f756-4259-b8bc-69e27580455e)

Thank you for your interest and support.

**Comment by fcorbelli** [comment] 2024-10-15 19:28
I don't quite understand what you want to do.
You can mark up a version, in zpaqfranz, with -comment something
path manipulation is not at all designed for some kind of “weird” archiving. It serves during the file extraction phase to put them in a different folder than they were originally in
```
zpaqfranz a z:\okane c:\nz -to "/whereveruno" -comment "uno"
zpaqfranz a z:\okane c:\1200 -to "/whereverdue" -comment "due"

zpaqfranz l z:\okane.zpaq -only "/whereverdue*" -comment "due"
```

**Comment by byplt** [comment] 2024-10-15 20:06
Let me explain it this way;

![image](https://github.com/user-attachments/assets/a8a9978a-271c-4043-beb0-59765bfa6702)

because I always need the latest version of the archive, working with "-until" and "-comment" too complicated for this situation

**Comment by fcorbelli** [comment] 2024-10-15 20:11
Why do you want the very same folder?
Do not use -to at all

**Comment by byplt** [comment] 2024-10-15 20:22
I have to use the -to switch; otherwise, I would have to move all the files into a single folder named 'folder,' (before of using zpaqfranz), which is not practical.

Why do I need this? I need drag-and-drop functionality, similar to a GUI version of an archiver. So, if I drop files into a folder (inside the archive), I need the -to switch.

**Comment by byplt** [comment] 2024-10-15 20:26
I know zpaq doesn't work with this logic, but it already has the -to capability, even though it only works partially.

**Comment by fcorbelli** [comment] 2024-10-15 20:33
This is weird but I can add a -nodelete switch 
The file list will only grow

**Comment by byplt** [comment] 2024-10-15 20:39
If this causes the growth, I don't know if it is a 'smarter' way.

**Comment by mirogeorg** [comment] 2024-10-15 22:32
Franco, reading this post, I am truly amazed at how you remember so many options. I guess the source code is often your help ;)

But where can we also read more in detail about them? Specifically, the -input option caught my attention. It's not in the Wiki, but that's where the detailed documentation should be, where a person can open it and read everything about option 'a' in depth.

In the command line help, it's mentioned in five words, but that help is too concise for someone to learn from it. It's more for reference, to remind oneself if they already know what they're doing.

The issue with -input -find -replace wasn't clear to me what it's caused by, but it gets resolved with -to. It really seems more intuitive and clear with -find and -replace, but if it doesn’t work... when and why, at least, I didn't understand... that should go to help, with examples, cases and their solution.

The proposed new  option -nodelete... it can't be explained in one line. I understood what it's for, but with just one line, it won't be clear ;)

**Comment by fcorbelli** [comment] 2024-10-16 08:42
> If this causes the growth, I don't know if it is a 'smarter' way.

You can try

**Comment by fcorbelli** [comment] 2024-10-16 08:50
> Franco, reading this post, I am truly amazed at how you remember so many options. I guess the source code is often your help ;)


I wrote them, so it is not that difficult. What is difficult are the portions written by Mahoney


 
> But where can we also read more in detail about them? Specifically, the -input option caught my attention. It's not in the Wiki, but that's where the detailed documentation should be, where a person can open it and read everything about option 'a' in depth.

Usually I write a couple of lines in the Release
Don't forget one key point. zpaqfranz I wrote it for my jobs, where I get paid. While I am not, to publish it
Even just writing two lines takes time, and especially when I have no feedback I am not stimulated


 
> In the command line help, it's mentioned in five words, but that help is too concise for someone to learn from it. It's more for reference, to remind oneself if they already know what they're doing.

True

> The issue with -input -find -replace wasn't clear to me what it's caused by, but it gets resolved with -to. It really seems more intuitive and clear with -find and -replace, but if it doesn’t work... when and why, at least, I didn't understand... that should go to help, with examples, cases and their solution.


wow, you really want a big explanation of how zpaq file nomenclature works, and zpaqfranz extensions?
It probably takes a couple of hours to write.
In this particular case, the drama is about using Windows-style (\) bars instead of zpaq-style (/) ones in paths. This is the short version
 
> The proposed new option -nodelete... it can't be explained in one line. I understood what it's for, but with just one line, it won't be clear ;)

I'll write it down in the meantime, then we'll see if it's of any use, in which case I'll write two lines 😄

**Comment by fcorbelli** [comment] 2024-10-16 08:54
Just a note. Mahoney is certainly a genius at writing compression algorithms, but he knows virtually nothing about backups; it's not his “world.” This causes zpaq to be born with serious flaws, and incredible complications.
Which, however, I did NOT remove, so as not to “break” backward compatibility. Virtually any zpaq command works identically on zpaqfranz (except for the -summary switch, which was so badly written that I changed it out of desperation). So if you ask yourself “why is there no uniform behavior? Why these strange things?” The answer is: backward compatibility. 
_Or is it a feature, not a bug_

**Comment by fcorbelli** [comment] 2024-10-16 08:55
BTW
```
	g_programflags.add(&flag715,			"-715",					"Runs just about like zpaq 7.15",					"a;");
	g_programflags.add(&flagappend,			"-append",				"Append-only (antiransomware, slow)",				"a;");
	g_programflags.add(&flagbackupxxh3,		"-backupxxh3",			"Use XXH3 in backup instead of MD5",				"");
	g_programflags.add(&flagbig,			"-big",					"Big",												"all;");
	g_programflags.add(&flagchecksum,		"-checksum",			"Do checksums",										"");
	g_programflags.add(&flagchecktxt,		"-checktxt",			"Checktxt (MD5)",									"");
#ifdef _WIN32
	g_programflags.add(&flagsfx,			"-sfx",					"Enable SFX module",								"");
#endif
	g_programflags.add(&flagfasttxt,		"-fasttxt",				"Create test .txt with CRC-32 and QUICK",											"");
	g_programflags.add(&flagcomment,		"-comment",				"Comment version",									"");
	g_programflags.add(&flagdebug,			"-debug",				"Show debug line number",							"");
	g_programflags.add(&flagdebug2,			"-debug2",				"Show debug infos",									"");
	g_programflags.add(&flagdebug3,			"-debug3",				"Show A LOT of debug",								"");
	g_programflags.add(&flagdebug4,			"-debug4",				"Write debug data on z:\\",							"");
	g_programflags.add(&flagdebug5,			"-debug5",				"Show RAM usage",							"");
	g_programflags.add(&flagdesc,			"-desc",				"Orderby desc",										"");
	g_programflags.add(&flagnosymlink,		"-symlink",				"Ignore Windows REPARSE_POINT (Symlink)",										"");
	g_programflags.add(&flagdonotforcexls,	"-xls",					"Do NOT force adding of XLS/PPT (default: NO)",		"a;");
	g_programflags.add(&flagdummy,			"-debug -zero -kill",	"Add 0-byte long file (debugging)",					"");
	g_programflags.add(&flagdummy,			"-debug -zero",			"Add files but zero-filled (debugging)",			"");
	g_programflags.add(&flagfilelist,		"-filelist",			"Create a filelist .txt",							"");
#ifdef _WIN32
	g_programflags.add(&flagads,			"-ads",					"Store filelists on NTFS",							"");
#endif
	g_programflags.add(&flagfast,			"-fast",				"Store filelists inside",							"");
	g_programflags.add(&flagfix255,			"-fix255",				"Fix 255",											"");
	g_programflags.add(&flagfixeml,			"-fixeml",				"Fix eml filenames",								"");
	g_programflags.add(&flagflat,			"-flat",				"Flat filenames",									"");
	g_programflags.add(&flagforce,			"-force",				"Force",											"");
	g_programflags.add(&flagforcewindows,	"-forcewindows",		"Store ADS stuff                (default: NO)",		"a;");
	g_programflags.add(&flagforcezfs,		"-forcezfs",			"Enforce using .zfs",								"");
	g_programflags.add(&flagfrugal,			"-frugal",				"Frugal backup",									"");
	g_programflags.add(&flaghashdeep,		"-hashdeep",			"Hashdeep",											"");
	g_programflags.add(&flagignore,			"-ignore",				"Ignore (do not show) file errors",												"a;");
	g_programflags.add(&flaghome,			"-home",				"Home",												"a;");
	g_programflags.add(&flagkill,			"-kill",				"Kill",												"");
	g_programflags.add(&flaght,				"-ht",					"Enable Hyperthread (if any)",												"");
	g_programflags.add(&flagnocaptcha,		"-nocaptcha",			"Skip chaptcha",												"");
	g_programflags.add(&flagmm,				"-mm",					"Memory mapped",									"");
	g_programflags.add(&flagnoattributes,	"-noattributes",		"Do not store attribute",									"");
	g_programflags.add(&flagattr,			"-attr",				"Show attribute (listing)",									"");
	g_programflags.add(&flagthunderbird,	"-thunderbird",			"Thunderbird's e-mail",									"");
	g_programflags.add(&flagnodedup,		"-nodedup",				"Turn off deduplicator",							"");
	g_programflags.add(&flagnoeta,			"-noeta",				"Do not show ETA",									"");
	g_programflags.add(&flagnopath,			"-nopath",				"Do not store path",								"");
	g_programflags.add(&flagnoqnap,			"-noqnap",				"Exclude QNAP snap & trash",						"a;");
	g_programflags.add(&flagnomac,			"-nomac",				"Exclude Mac hidden files",						"a;");
	g_programflags.add(&flagnosynology,		"-nosynology",			"Exclude Synology system files",						"a;");
	g_programflags.add(&flagnorecursion,	"-norecursion",			"Do not recurse into folders (default: YES)",		"");
	g_programflags.add(&flagnosort,			"-nosort",				"Do not sort file",									"");
	g_programflags.add(&flagpakka,			"-pakka",				"New output",										"");
	g_programflags.add(&flagdistinct,		"-distinct",			"PAKKA zpaqlist",										"");
	g_programflags.add(&flagparanoid,		"-paranoid",			"Paranoid",											"");
	///g_programflags.add(&flagpaq,			"-paq",					"Enable paq-levels",											"");
	g_programflags.add(&flagcollision,		"-collision",			"Collision check",											"");
	g_programflags.add(&flagramdisk,		"-ramdisk",				"Ramdisk (really: heap)",											"");
	g_programflags.add(&flagrename,			"-rename",				"Rename",											"");
	g_programflags.add(&flagsilent,			"-silent",				"Silent",											"");
	g_programflags.add(&flagnoconsole,		"-noconsole",			"Do not manipulate console",						"",flagnoconsole);
	g_programflags.add(&flagskipzfs,		"-zfs",					"Do NOT ignore .zfs             (default: YES)",	""); //flagskipzfs
	g_programflags.add(&flagspace,			"-space",				"Do not check space/writeability",					"");
	g_programflags.add(&flagssd,			"-ssd",					"SSD",												"");
	g_programflags.add(&flaghdd,			"-hdd",					"HDD",												"");
	g_programflags.add(&flagstat,			"-stat",				"Statistics",										"");
	g_programflags.add(&flagstdin,			"-stdin",				"stdin",											"");
	g_programflags.add(&flagterse,			"-terse",				"Create output without header and footer",			"");
	g_programflags.add(&flagnodel,			"-nodel",				"Do not show deleted files",			"");
	g_programflags.add(&flagstdout,			"-stdout",				"stdout",											"");
	g_programflags.add(&flagstore,			"-store",				"Store mode: no deduplication, no compression",		"");
	g_programflags.add(&flagtar,			"-tar",					"TAR mode (store posix)",							"");
	g_programflags.add(&flagtest,			"-test",				"Only do test",										"");
	g_programflags.add(&flagtouch,			"-touch",				"Force 'touch' on date (7.15 to zpaqfranz)",		"");
	g_programflags.add(&flagutc,			"-utc",					"Use UTC time",										"");
	g_programflags.add(&flagdate,			"-date",				"Show/save creation date (if possible)",			"");
	g_programflags.add(&flagutf,			"-utf",					"UTF-8",											"");
	g_programflags.add(&flagverbose,		"-verbose",				"Verbose output",									"");
	g_programflags.add(&flagverify,			"-verify",				"Verify",											"");
	g_programflags.add(&flagvss,			"-vss",					"Enable Volume Shadow Copies",						"a;");
	g_programflags.add(&flagzero,			"-zero",				"Flag zero",										"");
	g_programflags.add(&flagpause,			"-pause",				"Pause after run (for runhigh)",					"");
	g_programflags.add(&flagquiet,			"-quiet",				"Do not show filesystem errors",												"");

	g_programflags.add(&g_sfxflagforce,		"-sfxforce",			"Sfx force",									"");
	g_programflags.add(&g_sfxflagall,		"-sfxall",				"Sfx all",										"");

	g_programflags.add(&flagbarraod,		"/od",					"Order by date",									"dir;");
	g_programflags.add(&flagbarraon,		"/on",					"Order by name",									"dir;");
	g_programflags.add(&flagbarraos,		"/os",					"Order by size",									"dir;");

	g_programflags.add(&flagnocolor,		"-nocolor",				"Monochrome output",								"",flagnocolor);

#ifdef _WIN32
///	g_programflags.add(&flagdd,				"-dd",					"dd",												"");
	g_programflags.add(&flagfindzpaq,		"-findzpaq",			"Search .zpaq in every drive letter (USB device)",	"");
	g_programflags.add(&flagfixcase,		"-fixcase",				"Fix CAse",											"");
	g_programflags.add(&flagfixreserved,	"-fixreserved",			"fixreserved",										"");
	g_programflags.add(&flagimage,			"-image",				"Drive image",										"");
	g_programflags.add(&flaglongpath,		"-longpath",			"Longpath",											"");
	g_programflags.add(&flagopen,			"-open",				"open",												"");
#endif

	g_programflags.add(&flaghw,				"-hw",					"Use HW SHA1",										"a;x;");
```
+ more :)

**Comment by fcorbelli** [comment] 2024-10-16 09:10
> Let me explain it this way;
> 
> ![image](https://private-user-images.githubusercontent.com/48884110/376781688-a8a9978a-271c-4043-beb0-59765bfa6702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjg0MzUsIm5iZiI6MTcyOTA2ODEzNSwicGF0aCI6Ii80ODg4NDExMC8zNzY3ODE2ODgtYThhOTk3OGEtMjcxYy00MDQzLWJlYjAtNTk3NjViZmE2NzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA4NDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDRiMWEyM2E2NjI4MjM0ZjE1OTBkNWVjOTI3NGNlNzkwN2NhY2Y2ZTExYmE2MmJlOGMzOWQwYjhiNjJjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2QwNCa2L11pHkZA4bF7NbDCVD20j4ekxGHWr2nJRumw)
> 
> because I always need the latest version of the archive, working with "-until" and "-comment" too complicated for this situation

The problem is: what if the same filename is inside TWO folders?
What if in folderB there is a 1.txt too?

**Comment by fcorbelli** [comment] 2024-10-16 09:33
TRANSLATION
you have two folders
test1 with 1.txt, 2.txt
test2 with 1.txt, 3.txt, 4.txt
and you -to "/posizione"
The .zpaq will contain 1.txt from FOLDER2, 2.txt (folder1), 3.txt and 4.txt (folder2) if you archive test1 before test2

You will get something like
```
70156! *** UPDATED FILE with -nodelete *** <</posizione/1.txt>>
```
meaning that the file 1.txt is "overwritten" in the 2nd version (you can take it from the first, in this example)

**Comment by fcorbelli** [comment] 2024-10-16 13:40
OK, 60.8h just uploaded, with yellow warnings and red errors
CUL

**Comment by fcorbelli** [comment] 2024-10-16 13:55
> Franco, reading this post, I am truly amazed at how you remember so many options. I guess the source code is often your help ;)
> 
> But where can we also read more in detail about them?

We can make a deal
I write, YOU read, and report not so clear points

https://github.com/fcorbelli/zpaqfranz/wiki/Voodoo-switches

**Comment by byplt** [comment] 2024-10-16 18:04
Thanks! 
It seems to be working, and there is no growth issue. I will check it thoroughly

**Comment by fcorbelli** [comment] 2024-10-16 19:58
I can make the wiki writeable by anyone

**Comment by byplt** [comment] 2024-10-16 21:14
Thanks, everything seems to be working fine with the -nodelete switch.

I have a few suggestions:

If you think collision management is important (it’s not for me), you could introduce two different switches (instead of just -nodelete):

-preserve (like -nodelete, but with collision, so it overwrites)
-keep (like -nodelete, but no collisions)

These are just suggestions; I’m happy with -nodelete

------------------

By the way, does using the -range 0:9999999 switch achieve the same effect as -nodelete?"

Also, I would like to discuss some details about  "-input" switch tomorrow.

**Comment by mirogeorg** [comment] 2024-10-17 05:49
> I can make the wiki writeable by anyone

 I definitely would like to help with docs

**Comment by fcorbelli** [comment] 2024-10-18 07:12
> Thanks, everything seems to be working fine with the -nodelete switch.
> 
> I have a few suggestions:
> 
> If you think collision management is important (it’s not for me),

(...) not at all


> By the way, does using the -range 0:9999999 switch achieve the same effect as -nodelete?"

???
 
> Also, I would like to discuss some details about "-input" switch tomorrow.

**Comment by byplt** [comment] 2024-10-18 16:48
"-input" has great potential and is quite practical. However, we need a switch that provides destination paths, similar to the -to switch.

Example scenario;
![111](https://github.com/user-attachments/assets/70ba7333-72ff-404b-9d5f-9f32567586db)

With the new switch;
![22](https://github.com/user-attachments/assets/fce5a024-c7f5-4d05-83a9-a78ef98b7616)


Also;

with "-find" and "-replace" switchs, we can't achieve this scenario in one versioning, and the growth issue still occurs.
"-to" switch doesn’t work with "-input" and can’t set paths individually.


Note;

- What is "the growth problem"? It refers to the archive's file list growing because the same files are being archived repeatedly. The archive data itself won’t increase due to deduplication if the data is identical.
- Don't mind my "-range" switch question.

**Comment by fcorbelli** [comment] 2024-10-18 17:02
Please test the pre-release 60.8j (via zpaqfranz upgrade -force)

The growth problem concerns the ever-increasing possibility of name collisions, having essentially a potentially flat namespace. Incidentally, the list of files is stored, in blocks i, even if they are completely deduplicated (i.e., the data fragments are not written to the data blocks)

**Comment by byplt** [comment] 2024-10-18 17:22
Two issue exists;

- In the scenario, chatlogs.txt is not processed. I set its destination as a folder (you can see it in the scenario image), so the filenames shouldn’t matter for a folder destination. 

Output;
![image](https://github.com/user-attachments/assets/a3ee8c67-de17-42ff-b05f-8a979b0fe36e)

- Secondly, I added a new photo as 4.jpg, and it seems to have created a new folder. Is that expected?

Output;
![image](https://github.com/user-attachments/assets/f11072c3-1b4b-457e-9951-204ef492dc49)

**Comment by byplt** [comment] 2024-10-18 17:32
Actually, these issues aren't very important. I think it would be fine if it worked this way.

**Comment by byplt** [comment] 2024-10-18 17:34
You can restrict, the destination of a file input, must be file path.

**Comment by fcorbelli** [comment] 2024-10-18 17:36
> You can restrict, the destination of a file input, must be file path.

Ahemm... No
It's up to the user, if really want to mix some weird/strange options

**Comment by byplt** [comment] 2024-10-18 17:38
Thanks for your effort. I have a suggestion:

For the "-x" switch, you could implement the reverse of these operations.

For example:

`zpaqfranz x archive.zpaq -output "outputfiles.txt" -destination "destinations.txt"`

This is just a suggestion; I don’t need it.

**Comment by fcorbelli** [comment] 2024-10-18 17:40
> Thanks for your effort. I have a suggestion:
> 
> For the "-x" switch, you could implement the reverse of these operations.
> 
> For example:
> 
> `zpaqfranz x archive.zpaq -output "outputfiles.txt" -destination "destinations.txt"`
> 
> This is just a suggestion; I don’t need it.

Ahem... no
-destination will continue as multiple to
-input as multiple files

BTW you should to file to file, and folder to folder

filesandfolders.txt
```
c:\games\x\savegames\save1.dat
e:\apps\whatsapp\chatlogs.txt
c:\myfiles\photos\
```

destinations.txt
You can't to file to folder, or vice-versa
```
SaveGames\x_game_lastsavegame.dat
wpLogs\chatlogs.txt
myphotos\
```

**Comment by byplt** [comment] 2024-10-18 17:47
Thanks, there don’t seem to be any other problems. I didn’t realize that the "-input" and "-destination" switches also work for "-x".

**Comment by fcorbelli** [comment] 2024-10-18 17:48
They works everywhere

**Closed** 2024-10-18 18:18 UTC
